[workspace]

members = [
    "grownet_ui",
    "grownet_models",
    "grownet_macros"
]

resolver = "2"

[profile.test]
opt-level = 3

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
