[workspace]

members = [
    "grownet_ui",
    "grownet_models",
    "grownet_macros",
    "grownet_macro_core"
]

resolver = "2"

[profile.test]
opt-level = 3

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
debug = true