[package]
name = "grownet_macro_core"
version = "0.1.0"
edition = "2021"


[lib]
name = "grownet_macro_core"
path = "src/lib.rs"


[dependencies]
syn = { version = "*", features = ["extra-traits"] }
quote = "*"
proc-macro2 = "*"
anyhow = "1.0"
serde = "1.0.147"
ron = "0.8.0"