[package]
name = "grownet_macros"
version = "0.1.0"
edition = "2021"


[lib]
name = "grownet_macros"
path = "src/lib.rs"
proc-macro = true

[dependencies]
grownet_macro_core = { path = "../grownet_macro_core" }
proc-macro2 = "*"